/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Quick guide',
      link: {
        type: 'generated-index',
        title: 'Quick guide',
        description: 'Learn how to start using Noir.',
        slug: 'quick-guide',
        keywords: ['guide']
      },
      collapsed: true,
      collapsible: true,
      items: ['guide/invite', 'guide/setup', 'guide/welcome', 'guide/moderation', 'guide/punishment'],
    },
    {
      type: 'category',
      label: 'Moderation',
      link: {
        type: 'generated-index',
        title: 'Moderation',
        description: 'Moderation system resources.',
        slug: 'moderation',
        keywords: ['moderation']
      },
      collapsed: true,
      collapsible: true,
      items: ['moderation/rules', 'moderation/logs']
    },
    {
      type: 'category',
      label: 'Welcome',
      link: {
        type: 'generated-index',
        title: 'Welcome system',
        description: 'Powerful system to welcome new users in the best way.',
        slug: 'welcome',
        keywords: ['welcome']
      },
      collapsed: true,
      collapsible: true,
      items: ['welcome/message-editor', 'welcome/message-variables', 'welcome/image-variables']
    }
  ],
};

module.exports = sidebars;
